### ISSUE TITLE
docker-compose  up -l  results in an error related to src/test.py

### ISSUE THREAD

**Issue by thomashaensli** [swiss-art-research-net/sari-iiif-clip-search#3]
Hi @fkraeutli 

cloning the [sari-iiif-clip-search](https://github.com/swiss-art-research-net/sari-iiif-clip-search) app (branch `grp`) to rp1-prod.ethz.ch works, but an error message is being returned that seems to be related to `src/test.py`

Could you check on the error and how it could be resolved? 

Thanks, Thomas

```
rs@rs1-prod:~/sari-iiif-clip-search$ docker-compose up -d
Creating network "sari-iiif-clip-search_default" with the default driver
Building clip-service
[+] Building 89.7s (13/13) FINISHED                                                                                     docker:default
 => [internal] load build definition from Dockerfile                                                                              0.0s
 => => transferring dockerfile: 452B                                                                                              0.0s
 => [internal] load metadata for docker.io/library/python:3.8                                                                     1.3s
 => [internal] load .dockerignore                                                                                                 0.0s
 => => transferring context: 2B                                                                                                   0.0s
 => [internal] load build context                                                                                                 0.2s
 => => transferring context: 29.28MB                                                                                              0.2s
 => [1/9] FROM docker.io/library/python:3.8@sha256:e31986c72ec7f2a4e1c4d7a4e6034b5db537293b01df9192934ec028f762279e              12.3s
 => => resolve docker.io/library/python:3.8@sha256:e31986c72ec7f2a4e1c4d7a4e6034b5db537293b01df9192934ec028f762279e               0.0s
 => => sha256:e31986c72ec7f2a4e1c4d7a4e6034b5db537293b01df9192934ec028f762279e 1.86kB / 1.86kB                                    0.0s
 => => sha256:b22191dc7e2839324e89291f6a4b46d62e93af1732ac43b0cd94f9ae9cf56d19 7.36kB / 7.36kB                                    0.0s
 => => sha256:609c73876867487da051ad470002217da69bb052e2538710ade0730d893ff51f 49.56MB / 49.56MB                                  1.0s
 => => sha256:95f1e554af9c2ce17ccb9437e95e59cb015e1c2b0987f7ee0156cc94476fadcb 2.01kB / 2.01kB                                    0.0s
 => => sha256:7247ea8d81e671d079d67f3a9909315ef4641b45db90d62a1b18e3430c1937d4 24.05MB / 24.05MB                                  1.4s
 => => sha256:be374d06f38273b62ddd7aa5bc3ce3f9c781fd49a1f5a5dd94a46d2986920d7a 64.14MB / 64.14MB                                  1.3s
 => => extracting sha256:609c73876867487da051ad470002217da69bb052e2538710ade0730d893ff51f                                         2.1s
 => => sha256:b4580645a8e50b87a19330da289a9b1540022379f2c99d3f0112e3c5c4a8d051 211.14MB / 211.14MB                                4.0s
 => => sha256:aa7e0aca67ddfc342e2afe83df590a0e228e34781e7206639ddd9da72a71a0af 6.39MB / 6.39MB                                    1.9s
 => => sha256:32120056a9fe3594e5fbce0a5f08561ba976f9b52e8f14eccca9807fe6660741 15.20MB / 15.20MB                                  1.9s
 => => sha256:2fd0a626ceb4ced86afa0c52f8900554aefee83e12bf312b3b6d0af1e1f85e90 2.85MB / 2.85MB                                    2.1s
 => => sha256:19107d8e07f6a0b65356139c9458cce3955ee0fef09021002971ba919feb0d3f 245B / 245B                                        2.1s
 => => extracting sha256:7247ea8d81e671d079d67f3a9909315ef4641b45db90d62a1b18e3430c1937d4                                         0.6s
 => => extracting sha256:be374d06f38273b62ddd7aa5bc3ce3f9c781fd49a1f5a5dd94a46d2986920d7a                                         2.0s
 => => extracting sha256:b4580645a8e50b87a19330da289a9b1540022379f2c99d3f0112e3c5c4a8d051                                         4.9s
 => => extracting sha256:aa7e0aca67ddfc342e2afe83df590a0e228e34781e7206639ddd9da72a71a0af                                         0.2s
 => => extracting sha256:32120056a9fe3594e5fbce0a5f08561ba976f9b52e8f14eccca9807fe6660741                                         0.4s
 => => extracting sha256:19107d8e07f6a0b65356139c9458cce3955ee0fef09021002971ba919feb0d3f                                         0.0s
 => => extracting sha256:2fd0a626ceb4ced86afa0c52f8900554aefee83e12bf312b3b6d0af1e1f85e90                                         0.2s
 => [2/9] RUN mkdir /workdir                                                                                                      2.8s
 => [3/9] COPY ./requirements.txt /workdir/                                                                                       0.0s
 => [4/9] WORKDIR /workdir                                                                                                        0.1s
 => [5/9] RUN pip install -r requirements.txt                                                                                    68.7s
 => [6/9] RUN pip install flask requests waitress sari-sparql-parser==0.0.6                                                       3.1s
 => [7/9] ADD ./precomputedFeatures /precomputedFeatures                                                                          0.1s
 => [8/9] ADD ./src /workdir/src                                                                                                  0.0s
 => ERROR [9/9] RUN python src/test.py                                                                                            1.2s
------
 > [9/9] RUN python src/test.py:
1.003 Traceback (most recent call last):
1.003   File "src/test.py", line 1, in <module>
1.003     from sariIiifClipSearch import Query
1.003   File "/workdir/src/sariIiifClipSearch/__init__.py", line 1, in <module>
1.003     from .iiifClipSearch import *
1.003   File "/workdir/src/sariIiifClipSearch/iiifClipSearch.py", line 11, in <module>
1.003     from clip import clip
1.003   File "/workdir/src/clip/__init__.py", line 1, in <module>
1.003     from .clip import *
1.003   File "/workdir/src/clip/clip.py", line 28, in <module>
1.003     _tokenizer = _Tokenizer()
1.003   File "/workdir/src/sariIiifClipSearch/../clip/simple_tokenizer.py", line 66, in __init__
1.003     merges = gzip.open(bpe_path).read().decode("utf-8").split('\n')
1.003   File "/usr/local/lib/python3.8/gzip.py", line 292, in read
1.003     return self._buffer.read(size)
1.003   File "/usr/local/lib/python3.8/gzip.py", line 479, in read
1.003     if not self._read_gzip_header():
1.003   File "/usr/local/lib/python3.8/gzip.py", line 427, in _read_gzip_header
1.003     raise BadGzipFile('Not a gzipped file (%r)' % magic)
1.003 gzip.BadGzipFile: Not a gzipped file (b've')
------
Dockerfile:14
--------------------
  12 |     
  13 |     # Run once to download model to image
  14 | >>> RUN python src/test.py
  15 |     
  16 |     ENV FLASK_APP=/workdir/src/api.py
--------------------
ERROR: failed to solve: process "/bin/sh -c python src/test.py" did not complete successfully: exit code: 1
ERROR: Service 'clip-service' failed to build : Build failed

rs@rs1-prod:~/sari-iiif-clip-search$ 
```

**Comment by fkraeutli** [comment]
Try `docker-compose pull` so the image gets pulled rather than built on the server

**Comment by thomashaensli** [comment]
That helped, thanks for the help, but the process is exiting immediatly. 
I am on it...

**Comment by thomashaensli** [comment]
Hi  @fkraeutli

the process is still exiting immediatly after starting: 

```
rs@rs1-prod:~/sari-iiif-clip-search$ docker ps -a
CONTAINER ID   IMAGE                                                                    COMMAND                  CREATED          STATUS                      PORTS                                                                      NAMES
a8248e526fc1   swissartresearx/sari-iiif-clip-search:latest                             "/bin/sh -c 'flask r…"   21 minutes ago   Exited (1) 21 minutes ago                                                                              sari_clip_service
b1fae8595350   grp-setup_jobs                                                           "/bin/sh -c 'tail -f…"   9 days ago       Up 9 days                                                                                              grp-rs-prod_jobs
f6fd098b5c31   swissartresearx/researchspace:97aa754c63bfedf640904940be66b644ab536ab8   "/entrypoint.sh"         9 days ago       Up 9 days                   8080/tcp                                                                   grp-rs-prod_researchspace
4f36059fa5fa   robcast/researchspace-blazegraph:2.2.0-20160908                          "/entrypoint.sh"         9 days ago       Up 9 days                   8080/tcp                                                                   grp-rs-prod_blazegraph
c059cc13b740   nginx:1.19.2                                                             "/docker-entrypoint.…"   11 days ago      Up 11 days (healthy)        0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   nginx-proxy
ac3b4e403203   jrcs/letsencrypt-nginx-proxy-companion:v1.12.1                           "/bin/bash /app/entr…"   11 days ago      Up 11 days                                                                                             nginx-proxy-letsencrypt
872f1afeb566   jwilder/docker-gen:latest  
```

So far done: 
- git clone branch `grp`
- `docker-compose up -d` did result in error while build
- `docker pull` worked
- but container exits after start
- interface shows error 

Do you see where the problem is?

**Comment by fkraeutli** [comment]
Yep seems to be the case:
```
rs@rs1-prod:~/sari-iiif-clip-search$ cat src/clip/bpe_simple_vocab_16e6.txt.gz
version https://git-lfs.github.com/spec/v1
oid sha256:924691ac288e54409236115652ad4aa250f48203de50a9e4722a6ecd48d6804a
size 1356917
```
In your case it should only be `src/clip/bpe_simple_vocab_16e6.txt.gz` since the grp features don't use Git LFS

**Comment by thomashaensli** [comment]
Ok, stupid me: git-lfs was the last thing I would have look fir a bug...

- copying the file manually did not work (neither from the repo., nor from staging) 
- thus, I installed lfs and started over
- now the repo lives at `~/sari-iiif-clip-search-v2`
- the service starts and seems to remain stable


```
rs@rs1-prod:~/sari-iiif-clip-search-v2$ docker ps -a
CONTAINER ID   IMAGE                                                                    COMMAND                  CREATED          STATUS                    PORTS                                                                      NAMES
6e9cf464a71a   swissartresearx/sari-iiif-clip-search:latest                             "/bin/sh -c 'flask r…"   58 minutes ago   Up 58 minutes (healthy)   0.0.0.0:5000->5000/tcp, :::5000->5000/tcp                                  sari_clip_service
b1fae8595350   grp-setup_jobs                                                           "/bin/sh -c 'tail -f…"   10 days ago      Up 10 days                                                                                           grp-rs-prod_jobs
f6fd098b5c31   swissartresearx/researchspace:97aa754c63bfedf640904940be66b644ab536ab8   "/entrypoint.sh"         10 days ago      Up 10 days                8080/tcp                                                                   grp-rs-prod_researchspace
4f36059fa5fa   robcast/researchspace-blazegraph:2.2.0-20160908                          "/entrypoint.sh"         10 days ago      Up 9 days                 8080/tcp                                                                   grp-rs-prod_blazegraph
c059cc13b740   nginx:1.19.2                                                             "/docker-entrypoint.…"   11 days ago      Up 11 days (healthy)      0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   nginx-proxy
ac3b4e403203   jrcs/letsencrypt-nginx-proxy-companion:v1.12.1                           "/bin/bash /app/entr…"   11 days ago      Up 11 days                                                                                           nginx-proxy-letsencrypt
872f1afeb566   jwilder/docker-gen:latest                                                "/usr/local/bin/dock…"   11 days ago      Up 11 days                                                                                           nginx-proxy-gen
```

**Comment by thomashaensli** [comment]
However, in the frontend, errors are still being displayed. Here is what the log says: 

```
rs@rs1-prod:~/sari-iiif-clip-search-v2$ docker logs sari_clip_service
 * Serving Flask app '/workdir/src/api.py' (lazy loading)
 * Environment: development
 * Debug mode: on
/usr/local/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
 * Running on all addresses (0.0.0.0)
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://127.0.0.1:5000
 * Running on http://172.28.0.6:5000 (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 142-603-345
/usr/local/lib/python3.8/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0
127.0.0.1 - - [18/Apr/2024 12:04:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 12:09:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 12:14:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 12:19:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 12:24:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 12:29:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 12:34:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 12:39:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 12:44:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 12:49:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 12:54:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 12:59:38] "GET / HTTP/1.1" 200 -
10.6.96.182 - - [18/Apr/2024 13:02:59] code 400, message Bad request version ('Uµ!5ïì{\x9d:fî¯\x86\x13\x10ºà\xadÄ-i·äÕÈo\x12jà«°\x00*zz\x13\x01\x13\x02\x13\x03À,À+Ì©À0À/Ì¨À')
10.6.96.182 - - [18/Apr/2024 13:02:59] "üÚM«÷Å­ûÒì³^	ÅÛ6±ø«fTôã²D<g Uµ!5ïì{:fî¯ºà­Ä-i·äÕÈojà«°*zzÀ,À+Ì©À0À/Ì¨À" HTTPStatus.BAD_REQUEST -
10.6.96.182 - - [18/Apr/2024 13:02:59] code 400, message Bad request version ('\x93ÑõÎü\x90|2\x8cÎ>ÅÌo×0\x00,JJ\x13\x01\x13\x02\x13\x03À,À+Ì©À0À/Ì¨À')
10.6.96.182 - - [18/Apr/2024 13:02:59] "ü½$¦¹d°=!§³/¼úöêª	rk9¶º9y¥«WU qVm¢
                                                                                Æº	ÑõÎü|2Î>ÅÌo×0,JJÀ,À+Ì©À0À/Ì¨À" HTTPStatus.BAD_REQUEST -
10.6.96.182 - - [18/Apr/2024 13:02:59] code 400, message Bad request syntax ('\x16\x03\x01\x00ª\x01\x00\x00¦\x03\x01\x1ab¶\x13\x88\x0eüÙ=ä8¿\x03õ©³kK*\x82,äÙ\x90\x16^\x83\x102\x1b²}\x00\x00\x14À')
10.6.96.182 - - [18/Apr/2024 13:02:59] "ª¦b¶üÙ=ä8¿õ©³kK*,äÙ^2²À" HTTPStatus.BAD_REQUEST -
10.6.96.182 - - [18/Apr/2024 13:03:00] code 400, message Bad request version ('ÉÙv$:â>\x1aÓl\x8a¡\x00*\x9a\x9a\x13\x01\x13\x02\x13\x03À,À+Ì©À0À/Ì¨À')
10.6.96.182 - - [18/Apr/2024 13:03:00] "üªæ,¨ôj¬üï×¾þ«§Ë%yæZÛè	Óa)Z BC}+J¶ºm ôi> ÉÙv$:â>Ól¡*À,À+Ì©À0À/Ì¨À" HTTPStatus.BAD_REQUEST -
10.6.96.182 - - [18/Apr/2024 13:03:00] code 400, message Bad HTTP/0.9 request type ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\x9en\x88\x98d\x91Bk)ÈáVß²Íºs¯ç³f?gwdÉ]\x18µ\x88\x12F')
10.6.96.182 - - [18/Apr/2024 13:03:00] "ündBk)ÈáVß²Íºs¯ç³f?gwdÉ]µF ®ùÉ«ïñs'`ÖÌìÅÔ¬f×Ö¶ÖÑFñ¾åßª,êêÀ,À+Ì©À0À/Ì¨À" HTTPStatus.BAD_REQUEST -
10.6.96.182 - - [18/Apr/2024 13:03:00] code 400, message Bad request syntax ("\x16\x03\x01\x00ª\x01\x00\x00¦\x03\x01Ê*AUyÏÔ3Ñá\x88[d´á~\x00e\x90.½Ü'.`õo¼Á\x18?µ\x00\x00\x14À")
10.6.96.182 - - [18/Apr/2024 13:03:00] "ª¦Ê*AUyÏÔ3Ñá[d´á~e.½Ü'.`õo¼Á?µÀ" HTTPStatus.BAD_REQUEST -
127.0.0.1 - - [18/Apr/2024 13:04:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 13:09:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 13:14:38] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Apr/2024 13:19:39] "GET / HTTP/1.1" 200 -
```

Note: `10.6.96.182` is my client

**Comment by fkraeutli** [comment]
> Ok, stupid me: git-lfs was the last thing I would have look for a bug...

I added a helpful note https://github.com/swiss-art-research-net/sari-iiif-clip-search/commit/d2c7d3e7dcb4d13af4b188b0a8bc75ae3b4570b8

**Comment by fkraeutli** [comment]
> However, in the frontend, errors are still being displayed. Here is what the log says:
> 

That's fine. It runs in debug mode. It complains that there is no GPU acceleration but it works fine under CPU as well

**Comment by thomashaensli** [comment]
@fkraeutli 
I would be grateful, if you could have a closer look (since my expertise is ending...)

(I will have a look at the server alias in the mean time, then we can hope fully put the new production instance online)

**Comment by thomashaensli** [comment]
> > However, in the frontend, errors are still being displayed. Here is what the log says:
> 
> That's fine. It runs in debug mode. It complains that there is no GPU acceleration but it works fine under CPU as well

Sorry I did not add the screenshot: 
![Bildschirmfoto 2024-04-18 um 15 26 47](https://github.com/swiss-art-research-net/sari-iiif-clip-search/assets/30504518/b743a58f-d2bb-4a59-b569-161819fd48a1)

**Comment by fkraeutli** [comment]
I'll take a look

**Comment by fkraeutli** [comment]
The Service was attached to the proxy network. However, since it is queried through a SPARQL Service query, it needs to be in the internal Docker network where also Blazegraph is running. It needs to be exposed to Blazegraph (internally) not the outside world. I changed it and it looks like it's working.

**Comment by thomashaensli** [comment]
Thanks, @fkraeutli!

> The Service was attached to the proxy network. However, since it is queried through a SPARQL Service query, it needs to be in the internal Docker network where also Blazegraph is running. 

 Clever, so that is how we make sure only RS is exposed to the outside proxy network, but blazegraph and the clip service are not. 
 
 Got the point! Thanks for the help and lesson..

**Comment by fkraeutli** [comment]
You're welcome! I'll delete this issue since the repo is public
